# ████████████████████████████████████████████████████████████████████
# ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
# ██████╗ ██╗ ██████╗ ██╗██╗   ██╗ █████╗ ████████╗ █████╗ ██████╗
# ██╔══██╗██║██╔════╝ ██║██║   ██║██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗
# ██║  ██║██║██║  ███╗██║██║   ██║███████║   ██║   ███████║██████╔╝
# ██║  ██║██║██║   ██║██║╚██╗ ██╔╝██╔══██║   ██║   ██╔══██║██╔══██╗
# ██████╔╝██║╚██████╔╝██║ ╚████╔╝ ██║  ██║   ██║   ██║  ██║██║  ██║
# ╚═════╝ ╚═╝ ╚═════╝ ╚═╝  ╚═══╝  ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
# ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
# ████████████████████████████████████████████████████████████████████
#
#  ◈ Another master codex from Digivatar
#  ◈ Avant-garde digital visual world-building and music artist
#  ◈ github.com/Master-Zomon  |  digivatar.com
# ───────────────────────────────────────────────────────────────────

# ◈ DIGIVATAR — digivatar-pixel-assembly — embed.py

"""
digivatar-pixel-assembly — embed.py
=====================================
Converts the standalone output.html (from encode.py) into a
page-embed version that triggers as the user scrolls to that
section of your site.

Usage:
    python embed.py output.html
    python embed.py output.html --output my_section.html

What it produces:
    embed_section.html  — paste this <section> block into your page HTML
    digivatar-data.js   — external data file (keeps your page load fast)

The scroll listener is rewritten to track the section's position
on the page rather than the mouse wheel.
Compatible with: plain HTML, WordPress, Webflow, React.
"""

import re
import sys
import argparse
from pathlib import Path


# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  E X T R A C T  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
# Pull the pieces we need out of the standalone HTML file.

def extract_b64(content):
    """Extract the base64 pixel blob from the HTML file."""
    match = re.search(r'const B64\s*=\s*"([^"]+)";', content)
    if not match:
        print("ERROR: Could not find B64 data in HTML.")
        print("       Make sure this file was generated by encode.py.")
        sys.exit(1)
    return match.group(1)


def extract_script(content):
    """Extract the full <script> block content."""
    match = re.search(r'<script>(.*?)</script>', content, re.DOTALL)
    if not match:
        print("ERROR: Could not find <script> block in HTML.")
        sys.exit(1)
    return match.group(1)


def extract_styles(content):
    """Extract the <style> block content."""
    match = re.search(r'<style>(.*?)</style>', content, re.DOTALL)
    return match.group(1) if match else ''


def extract_element_text(content, element_id):
    """Extract the inner text of an element by ID."""
    match = re.search(rf'<div id="{element_id}">(.*?)</div>', content, re.DOTALL)
    return match.group(1) if match else ''


# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  R E W R I T E  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
# Rewrite the standalone JS to work as a page section.

def rewrite_canvas_sizing(script, section_id):
    """
    Swap fullscreen canvas sizing for section-relative sizing.
    The canvas fills its parent section instead of the whole window.
    """
    script = script.replace(
        'canvas.width=window.innerWidth;',
        f'canvas.width=document.getElementById("{section_id}").offsetWidth;'
    )
    script = script.replace(
        'canvas.height=window.innerHeight;',
        f'canvas.height=document.getElementById("{section_id}").offsetHeight;'
    )
    # also fix the resize listener
    script = script.replace(
        "window.addEventListener('resize', () => {\n  canvas.width  = window.innerWidth;\n  canvas.height = window.innerHeight;\n});",
        f"window.addEventListener('resize', () => {{\n  const sec = document.getElementById('{section_id}');\n  canvas.width  = sec.offsetWidth;\n  canvas.height = sec.offsetHeight;\n}});"
    )
    return script


def rewrite_scroll_listener(script):
    """
    Replace the wheel event listener with a scroll position listener.
    Assembly progress is driven by how far the section has scrolled into view.
    """
    # match the wheel listener block
    wheel_pattern = r"window\.addEventListener\('wheel'.*?\}\s*,\s*\{[^}]*\}\s*\)\s*;"
    scroll_listener = (
        "window.addEventListener('scroll', () => {\n"
        "  const rect     = section.getBoundingClientRect();\n"
        "  const scrolled = -rect.top / rect.height;   // 0 = section entering, 1 = fully scrolled\n"
        "  tgt = Math.max(0, Math.min(1, scrolled));\n"
        "});"
    )
    rewritten, count = re.subn(wheel_pattern, scroll_listener, script, flags=re.DOTALL)
    if count == 0:
        print("WARNING: Could not find wheel listener to rewrite. Scroll trigger may not work.")
    return rewritten


def scope_styles(styles, section_id):
    """Scope CSS selectors to the section so they don't leak into the host page."""
    styles = styles.replace('body{',    f'#{section_id}{{')
    styles = styles.replace('canvas{',  f'#{section_id} canvas{{')
    styles = styles.replace('#ui{',     f'#{section_id}-ui{{')
    styles = styles.replace('#lbl{',    f'#{section_id}-lbl{{')
    return styles


def update_element_ids(script, section_id):
    """Update getElementById calls to use the scoped element IDs."""
    script = script.replace(
        "document.getElementById('lbl')",
        f"document.getElementById('{section_id}-lbl')"
    )
    script = script.replace(
        "document.getElementById('ui')",
        f"document.getElementById('{section_id}-ui')"
    )
    return script


# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  B U I L D  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
# Assemble the final embed block.

def build_embed(script, styles, lbl_text, ui_text, data_file, section_id):
    """Build the complete embeddable HTML block."""

    # add section reference at top of script
    script = f"const section = document.getElementById('{section_id}');\n\n" + script

    return f'''<!--
  ◈ DIGIVATAR — digivatar-pixel-assembly — embed block
  ──────────────────────────────────────────────────────
  Paste this into your page where you want the effect to appear.
  Also copy {data_file} to your site and include it before this block:

    <script src="{data_file}"></script>

  Works with: plain HTML, WordPress, Webflow, React.
-->

<style>
{styles}
#{section_id} {{
  position: relative;
  width: 100%;
  height: 100vh;
  overflow: hidden;
}}
</style>

<section id="{section_id}">
  <canvas id="c"></canvas>
  <div id="{section_id}-lbl">{lbl_text}</div>
  <div id="{section_id}-ui">{ui_text}</div>
</section>

<script src="{data_file}"></script>
<script>
{script}
</script>
'''


# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  E N T R Y  P O I N T  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
# Parse args, run conversion, write output files.

def main():
    parser = argparse.ArgumentParser(
        description='Convert standalone pixel assembly HTML to a page-embed section.'
    )
    parser.add_argument(
        'input',
        help='Path to output.html from encode.py'
    )
    parser.add_argument(
        '--output', '-o',
        default='embed_section.html',
        help='Output filename for the embed block (default: embed_section.html)'
    )
    parser.add_argument(
        '--data-file',
        default='digivatar-data.js',
        help='External data JS filename (default: digivatar-data.js)'
    )
    parser.add_argument(
        '--section-id',
        default='pixel-assembly-section',
        help='HTML ID for the section element (default: pixel-assembly-section)'
    )
    args = parser.parse_args()

    in_path = Path(args.input)
    if not in_path.exists():
        print(f"ERROR: File not found: {in_path}")
        sys.exit(1)

    print(f"Reading {in_path.name}...")
    content = in_path.read_text(encoding='utf-8')

    # ── extract ────────────────────────────────────────────────────────
    b64      = extract_b64(content)
    script   = extract_script(content)
    styles   = extract_styles(content)
    lbl_text = extract_element_text(content, 'lbl') or 'SCROLL TO ASSEMBLE'
    ui_text  = extract_element_text(content, 'ui')  or 'SCROLL TO ASSEMBLE'

    print(f"Extracted: {len(b64) // 1024} KB pixel data, {len(script) // 1024} KB script")

    # ── rewrite ────────────────────────────────────────────────────────
    script = script.replace(f'const B64 = "{b64}";', '/* B64 loaded from external data file */')
    script = rewrite_canvas_sizing(script, args.section_id)
    script = rewrite_scroll_listener(script)
    script = update_element_ids(script, args.section_id)
    styles = scope_styles(styles, args.section_id)

    # ── write data file ────────────────────────────────────────────────
    data_path = Path(args.data_file)
    data_path.write_text(f'// ◈ DIGIVATAR — pixel data\nconst B64 = "{b64}";\n', encoding='utf-8')
    print(f"Data file: {data_path} ({data_path.stat().st_size // 1024} KB)")

    # ── write embed block ──────────────────────────────────────────────
    embed    = build_embed(script, styles, lbl_text, ui_text, args.data_file, args.section_id)
    out_path = Path(args.output)
    out_path.write_text(embed, encoding='utf-8')
    print(f"Embed block: {out_path}")

    print()
    print("Next steps:")
    print(f"  1. Copy {data_path} to your site's root or assets folder")
    print(f"  2. Paste the contents of {out_path} into your page HTML")
    print(f"  3. The effect triggers as the user scrolls into the section")


if __name__ == '__main__':
    main()

# ◈ end of codex — Digivatar
