# ████████████████████████████████████████████████████████████████████
# ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
# ██████╗ ██╗ ██████╗ ██╗██╗   ██╗ █████╗ ████████╗ █████╗ ██████╗
# ██╔══██╗██║██╔════╝ ██║██║   ██║██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗
# ██║  ██║██║██║  ███╗██║██║   ██║███████║   ██║   ███████║██████╔╝
# ██║  ██║██║██║   ██║██║╚██╗ ██╔╝██╔══██║   ██║   ██╔══██║██╔══██╗
# ██████╔╝██║╚██████╔╝██║ ╚████╔╝ ██║  ██║   ██║   ██║  ██║██║  ██║
# ╚═════╝ ╚═╝ ╚═════╝ ╚═╝  ╚═══╝  ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
# ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
# ████████████████████████████████████████████████████████████████████
#
#  ◈ Another master codex from Digivatar
#  ◈ Avant-garde digital visual world-building and music artist
#  ◈ github.com/Master-Zomon  |  digivatar.com
# ───────────────────────────────────────────────────────────────────

# ◈ DIGIVATAR — digivatar-pixel-assembly — embed.py

"""
digivatar-pixel-assembly — embed.py
=====================================
Converts the standalone output.html (from encode.py) into a
page-embed version that triggers as the user scrolls to that
section of your site.

Usage:
    python embed.py output.html
    python embed.py output.html --output my_section.html

What it produces:
    embed_section.html  — paste this <section> block into your page HTML
    digivatar-data.js   — external data file (keeps your page load fast)

The scroll listener is rewritten to track the section's position
on the page rather than the mouse wheel.
Compatible with: plain HTML, WordPress, Webflow, React.
"""

import re
import sys
import argparse
from pathlib import Path


# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  E X T R A C T  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
# Pull the pieces we need out of the standalone HTML file.

def extract_b64(content):
    """Extract the base64 pixel blob from the HTML file."""
    match = re.search(r'const B64\s*=\s*"([^"]+)";', content)
    if not match:
        print("ERROR: Could not find B64 data in HTML.")
        print("       Make sure this file was generated by encode.py.")
        sys.exit(1)
    return match.group(1)


def extract_script(content):
    """Extract the full <script> block content."""
    match = re.search(r'<script>(.*?)</script>', content, re.DOTALL)
    if not match:
        print("ERROR: Could not find <script> block in HTML.")
        sys.exit(1)
    return match.group(1)


def extract_styles(content):
    """Extract the <style> block content."""
    match = re.search(r'<style>(.*?)</style>', content, re.DOTALL)
    return match.group(1) if match else ''


def extract_lbl_text(content):
    """Extract the label text from #lbl element."""
    match = re.search(r'<div id="lbl">([^<]*)</div>', content)
    return match.group(1).strip() if match else 'SCROLL TO ASSEMBLE'


def extract_controls_html(content):
    """
    Extract the full #ui controls block (toggle button + CRT panel).
    This is the complete structure — not just inner text.
    """
    match = re.search(r'(<div id="ui">.*?</div>\s*</div>\s*</div>)', content, re.DOTALL)
    if match:
        return match.group(1)
    # fallback — return a minimal toggle if structure not found
    return '<div id="ui"><div id="ui-toggle">C O N T R O L S &nbsp;&#9662;</div></div>'


# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  R E W R I T E  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
# Rewrite the standalone JS to work as a page section.

def rewrite_canvas_sizing(script, section_id):
    """
    Swap fullscreen canvas sizing for section-relative sizing.
    The canvas fills its parent section instead of the whole window.
    """
    script = script.replace(
        'canvas.width=window.innerWidth;',
        f'canvas.width=document.getElementById("{section_id}").offsetWidth;'
    )
    script = script.replace(
        'canvas.height=window.innerHeight;',
        f'canvas.height=document.getElementById("{section_id}").offsetHeight;'
    )
    script = script.replace(
        "window.addEventListener('resize', () => {\n  canvas.width  = window.innerWidth;\n  canvas.height = window.innerHeight;\n});",
        f"window.addEventListener('resize', () => {{\n  const sec = document.getElementById('{section_id}');\n  canvas.width  = sec.offsetWidth;\n  canvas.height = sec.offsetHeight;\n}});"
    )
    return script


def rewrite_scroll_listener(script):
    """
    Replace the wheel event listener with a scroll position listener.
    Assembly progress is driven by how far the section has scrolled into view.
    """
    wheel_pattern = r"window\.addEventListener\('wheel'.*?\}\s*,\s*\{[^}]*\}\s*\)\s*;"
    scroll_listener = (
        "window.addEventListener('scroll', () => {\n"
        "  const rect     = section.getBoundingClientRect();\n"
        "  const scrolled = -rect.top / rect.height;\n"
        "  tgt = Math.max(0, Math.min(1, scrolled));\n"
        "});"
    )
    rewritten, count = re.subn(wheel_pattern, scroll_listener, script, flags=re.DOTALL)
    if count == 0:
        print("WARNING: Could not find wheel listener to rewrite. Scroll trigger may not work.")
    return rewritten


def scope_styles(styles, section_id):
    """
    Scope CSS selectors to the section so they don't leak into the host page.
    Covers all CRT panel IDs introduced in the current controls system.
    """
    replacements = [
        ('body {',         f'#{section_id} {{'),
        ('canvas {',       f'#{section_id} canvas {{'),
        ('#lbl {',         f'#{section_id}-lbl {{'),
        ('#ui {',          f'#{section_id}-ui {{'),
        ('#ui-toggle {',   f'#{section_id}-ui-toggle {{'),
        ('#ui-toggle:hover', f'#{section_id}-ui-toggle:hover'),
        ('#crt-wrap {',    f'#{section_id}-crt-wrap {{'),
        ('#crt-panel {',   f'#{section_id}-crt-panel {{'),
        ('#crt-panel .s {',f'#{section_id}-crt-panel .s {{'),
        ('#crt-panel .s:first-child {', f'#{section_id}-crt-panel .s:first-child {{'),
        ('#crt-scan {',    f'#{section_id}-crt-scan {{'),
        ('#crt-noise-a,',  f'#{section_id}-crt-noise-a,'),
        ('#crt-noise-b {', f'#{section_id}-crt-noise-b {{'),
        ('#crt-noise-a {', f'#{section_id}-crt-noise-a {{'),
        ('#line-a {',      f'#{section_id}-line-a {{'),
        ('#line-b {',      f'#{section_id}-line-b {{'),
        ('#line-c {',      f'#{section_id}-line-c {{'),
        ('#line-d {',      f'#{section_id}-line-d {{'),
        ('#line-e {',      f'#{section_id}-line-e {{'),
        ('#line-a .crt-line-inner {', f'#{section_id}-line-a .crt-line-inner {{'),
        ('#line-b .crt-line-inner {', f'#{section_id}-line-b .crt-line-inner {{'),
        ('#line-c .crt-line-inner {', f'#{section_id}-line-c .crt-line-inner {{'),
        ('#line-d .crt-line-inner {', f'#{section_id}-line-d .crt-line-inner {{'),
        ('#line-e .crt-line-inner {', f'#{section_id}-line-e .crt-line-inner {{'),
        ('#crt-wrap.phase-dot',    f'#{section_id}-crt-wrap.phase-dot'),
        ('#crt-wrap.phase-expand', f'#{section_id}-crt-wrap.phase-expand'),
        ('#crt-wrap.closing',      f'#{section_id}-crt-wrap.closing'),
    ]
    for old, new in replacements:
        styles = styles.replace(old, new)
    return styles


def update_element_ids(script, section_id):
    """
    Update all getElementById calls to use the scoped element IDs.
    Covers the label, toggle button, and CRT wrap — all active JS references.
    """
    id_map = {
        "getElementById('lbl')":        f"getElementById('{section_id}-lbl')",
        "getElementById('ui-toggle')":  f"getElementById('{section_id}-ui-toggle')",
        "getElementById('crt-wrap')":   f"getElementById('{section_id}-crt-wrap')",
    }
    for old, new in id_map.items():
        script = script.replace(f'document.{old}', f'document.{new}')
    return script


# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  B U I L D  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
# Assemble the final embed block.

def scope_html_ids(controls_html, section_id):
    """
    Prefix all element IDs and matching data attributes in the controls HTML
    so they match the scoped CSS and JS.
    """
    id_map = {
        'id="ui"':          f'id="{section_id}-ui"',
        'id="ui-toggle"':   f'id="{section_id}-ui-toggle"',
        'id="crt-wrap"':    f'id="{section_id}-crt-wrap"',
        'id="crt-panel"':   f'id="{section_id}-crt-panel"',
        'id="crt-scan"':    f'id="{section_id}-crt-scan"',
        'id="crt-noise-a"': f'id="{section_id}-crt-noise-a"',
        'id="crt-noise-b"': f'id="{section_id}-crt-noise-b"',
        'id="line-a"':      f'id="{section_id}-line-a"',
        'id="line-b"':      f'id="{section_id}-line-b"',
        'id="line-c"':      f'id="{section_id}-line-c"',
        'id="line-d"':      f'id="{section_id}-line-d"',
        'id="line-e"':      f'id="{section_id}-line-e"',
    }
    for old, new in id_map.items():
        controls_html = controls_html.replace(old, new)
    return controls_html


def build_embed(script, styles, lbl_text, controls_html, data_file, section_id):
    """Build the complete embeddable HTML block."""

    script = f"const section = document.getElementById('{section_id}');\n\n" + script

    return f'''<!--
  ◈ DIGIVATAR — digivatar-pixel-assembly — embed block
  ──────────────────────────────────────────────────────
  Paste this into your page where you want the effect to appear.
  Also copy {data_file} to your site and include it before this block:

    <script src="{data_file}"></script>

  Works with: plain HTML, WordPress, Webflow, React.
-->

<style>
{styles}
#{section_id} {{
  position: relative;
  width: 100%;
  height: 100vh;
  overflow: hidden;
}}
</style>

<section id="{section_id}">
  <canvas id="c"></canvas>
  <div id="{section_id}-lbl">{lbl_text}</div>
  {controls_html}
</section>

<script src="{data_file}"></script>
<script>
{script}
</script>
'''


# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  E N T R Y  P O I N T  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

def main():
    parser = argparse.ArgumentParser(
        description='Convert standalone pixel assembly HTML to a page-embed section.'
    )
    parser.add_argument('input', help='Path to output.html from encode.py')
    parser.add_argument('--output', '-o', default='embed_section.html',
        help='Output filename for the embed block (default: embed_section.html)')
    parser.add_argument('--data-file', default='digivatar-data.js',
        help='External data JS filename (default: digivatar-data.js)')
    parser.add_argument('--section-id', default='pixel-assembly-section',
        help='HTML ID for the section element (default: pixel-assembly-section)')
    args = parser.parse_args()

    in_path = Path(args.input)
    if not in_path.exists():
        print(f"ERROR: File not found: {in_path}")
        sys.exit(1)

    print(f"Reading {in_path.name}...")
    content = in_path.read_text(encoding='utf-8')

    # ── extract ────────────────────────────────────────────────────────
    b64          = extract_b64(content)
    script       = extract_script(content)
    styles       = extract_styles(content)
    lbl_text     = extract_lbl_text(content)
    controls_html = extract_controls_html(content)

    print(f"Extracted: {len(b64) // 1024} KB pixel data, {len(script) // 1024} KB script")

    # ── rewrite ────────────────────────────────────────────────────────
    script        = script.replace(f'const B64 = "{b64}";', '/* B64 loaded from external data file */')
    script        = rewrite_canvas_sizing(script, args.section_id)
    script        = rewrite_scroll_listener(script)
    script        = update_element_ids(script, args.section_id)
    styles        = scope_styles(styles, args.section_id)
    controls_html = scope_html_ids(controls_html, args.section_id)

    # ── write data file ────────────────────────────────────────────────
    data_path = Path(args.data_file)
    data_path.write_text(f'// ◈ DIGIVATAR — pixel data\nconst B64 = "{b64}";\n', encoding='utf-8')
    print(f"Data file: {data_path} ({data_path.stat().st_size // 1024} KB)")

    # ── write embed block ──────────────────────────────────────────────
    embed    = build_embed(script, styles, lbl_text, controls_html, args.data_file, args.section_id)
    out_path = Path(args.output)
    out_path.write_text(embed, encoding='utf-8')
    print(f"Embed block: {out_path}")

    print()
    print("Next steps:")
    print(f"  1. Copy {data_path} to your site's root or assets folder")
    print(f"  2. Paste the contents of {out_path} into your page HTML")
    print(f"  3. The effect triggers as the user scrolls into the section")


if __name__ == '__main__':
    main()

# If this codex helped you — donate to starving artist digivatar.eth
# ◈ end of codex — Digivatar
